name: Test feature branch

on:
  push:
    branches:
      - feat/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14
        uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies # Install all deps
        run: yarn

      - name: Sync versions # Sync versions
        run: yarn syncprojects

      - name: Build demo app # Build Schematics and move
        run: yarn build:demo --base-href https://bartholomej.github.io/ngx-translate-cut/

      - name: Build ngx-translate-cut # Build
        run: yarn build

      - name: Run tests
        run: yarn test --configuration=ci
